permalink: /:year/:month/:title
title: Alex Petrache
author: 
  name: Alex Petrache
  email: hello@alexand.ro
description: Pursuing the world of startups. Creating videos @Jurnalul Unui Olimpic. Ex-Software Engineer @Amazon.
url: "https://alexand.ro"
twitter:
  username: "AlexIPetrache"
facebook:
  app_id: 239202243681974
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
social:
  name: Alex Petrache
  links:
    - https://twitter.com/AlexIPetrache
    - https://www.facebook.com/petrache.alex
    - https://www.linkedin.com/in/alexpetrache
    - https://github.com/AlexPetrache
    - https://instagram.com/alexand.ro
    - https://youtube.com/channel/UCQQwkvM9vQ6AEl1CfnEtdrQ