permalink: /:year/:month/:title
title: Alex Petrache
email: hello@alexand.ro
description: Pursuing the world of startups. Creating videos @<a href="https://www.youtube.com/playlist?list=PL_O27Ff-lt5A6oQa7LXQVsGiHzPIq1iwt">Jurnalul Unui Olimpic</a>. Ex-Software Engineer @Amazon.
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
social:
  name: Alex Petrache
  links:
    - https://twitter.com/AlexIPetrache
    - https://www.facebook.com/petrache.alex
    - https://www.linkedin.com/in/alexpetrache
    - https://github.com/AlexPetrache
    - https://instagram.com/alexand.ro
    - https://youtube.com/channel/UCQQwkvM9vQ6AEl1CfnEtdrQ